---
title: "PA1-template"
author: "Fathy Eltanany"
date: "June 13, 2017"
output: html_document
---

Reproducible Research: Course Project 1
=================================================
## Loading Data
```{r}
data<- read.csv("activity.csv")
```
--------------------------------------------
## Mean total number of steps taken per day 

```{r}
library(ggplot2)
steps <- tapply(data$steps, data$date, FUN=sum, na.rm=TRUE)
qplot(steps, binwidth=1000, xlab="total number of steps")
mean(steps, na.rm=TRUE)
```
--------------------------------------------
## The average daily activity pattern
```{r}
library(ggplot2)
averages <- aggregate(x=list(steps=data$steps), by=list(interval=data$interval),
                      FUN=mean, na.rm=TRUE)
ggplot(data=averages, aes(x=interval, y=steps)) +
    geom_line() +
    xlab("5-minute interval") +
    ylab("average number of steps taken")
```

### Maximum number of steps in 5 minutes interval

```{r}
averages[which.max(averages$steps),]
```
--------------------------------------------
## Imputing missing values
total number of missing values in the dataset 

```{r}
missing <- is.na(data$steps)
table(missing)
```


fill in with mean value for that 5-minute interval.
```{r}
fill.value <- function(steps, interval) {
    filled <- NA
    if (!is.na(steps))
        filled <- c(steps)
    else
        filled <- (averages[averages$interval==interval, "steps"])
    return(filled)
}

#create new data set without NAs
filled.data <- data
filled.data$steps <- mapply(fill.value, filled.data$steps, filled.data$interval)

```

Making the histogram 
```{r}
steps <- tapply(filled.data$steps, filled.data$date, FUN=sum)
qplot(steps, binwidth=1000, xlab="total number of steps taken each day")
```
--------------------------------------------
## Differences in activity patterns between weekdays and weekends   

```{r}
weekdays <- function(date) {
    day <- weekdays(date)
    if (day %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"))
        return("weekday")
    else if (day %in% c("Saturday", "Sunday"))
        return("weekend")
}
filled.data$date <- as.Date(filled.data$date)
filled.data$day <- sapply(filled.data$date, FUN=weekdays)
```

panel plot containing plots of average number of steps taken on weekdays and weekends.
```{r}
averages <- aggregate(steps ~ interval + day, data=filled.data, mean)
ggplot(averages, aes(interval, steps)) + geom_line() + facet_grid(day ~ .) +
    xlab("5-minute interval") + ylab("Number of steps")
```
